# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

_file_map = {

    "agent_action.baml": "// Structured agent action — mirrors src/agents/schema.py LLMActionOutput contract.\n\nenum AgentIntent {\n  PursueTarget @description(\"Move toward or intercept a target\")\n  PursueMemory @description(\"Move toward last known position\")\n  FleeThreat @description(\"Move away from threats\")\n  HoldPosition\n  ExploreArea\n  SearchSystematic\n  Regroup\n  SignalTeammates\n  CutOff\n  HoldChokepoint\n  Bait\n  Unknown\n}\n\nclass CoordMessage {\n  payload float[]\n  channel string?\n}\n\nclass AgentAction {\n  intent AgentIntent\n  target_position float[]? @description(\"World [x, y]; preferred over movement\")\n  target_description string?\n  confidence float\n  movement float[]? @description(\"Deprecated [dx, dy, dz]; null when using target_position\")\n  message CoordMessage?\n}\n\n// Same prompts as prompts.py — passed through so before/after use identical instructions.\nfunction ChooseAgentAction(system_prompt: string, user_prompt: string) -> AgentAction {\n  client GroqLlama\n  prompt #\"\n    {{ _.role(\"system\") }}\n    {{ system_prompt }}\n\n    {{ _.role(\"user\") }}\n    {{ user_prompt }}\n\n    {{ ctx.output_format }}\n  \"#\n}\n",
    "clients.baml": "// Groq via OpenAI-compatible API (same endpoint as src/agents/clients/groq_client.py).\n\nclient<llm> GroqLlama {\n  provider openai-generic\n  options {\n    base_url \"https://api.groq.com/openai/v1\"\n    api_key env.GROQ_API_KEY\n    model \"llama-3.3-70b-versatile\"\n    temperature 0.2\n  }\n}\n",
    "generators.baml": "generator target {\n  output_type python/pydantic\n  output_dir \"../baml_client\"\n  version \"0.222.0\"\n}\n",
}

def get_baml_files():
    return _file_map