# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (2)
# #########################################################################

class AgentAction(BaseModel):
    intent: typing.Optional[types.AgentIntent] = None
    target_position: typing.Optional[typing.List[float]] = Field(default=None, description='World [x, y]; preferred over movement')
    target_description: typing.Optional[str] = None
    confidence: typing.Optional[float] = None
    movement: typing.Optional[typing.List[float]] = Field(default=None, description='Deprecated [dx, dy, dz]; null when using target_position')
    message: typing.Optional["CoordMessage"] = None

class CoordMessage(BaseModel):
    payload: typing.List[float]
    channel: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
