# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (1)
# #########################################################################

class AgentIntent(str, Enum):
    PursueTarget = "PursueTarget"
    PursueMemory = "PursueMemory"
    FleeThreat = "FleeThreat"
    HoldPosition = "HoldPosition"
    ExploreArea = "ExploreArea"
    SearchSystematic = "SearchSystematic"
    Regroup = "Regroup"
    SignalTeammates = "SignalTeammates"
    CutOff = "CutOff"
    HoldChokepoint = "HoldChokepoint"
    Bait = "Bait"
    Unknown = "Unknown"

# #########################################################################
# Generated classes (2)
# #########################################################################

class AgentAction(BaseModel):
    intent: AgentIntent
    target_position: typing.Optional[typing.List[float]] = Field(default=None, description='World [x, y]; preferred over movement')
    target_description: typing.Optional[str] = None
    confidence: float
    movement: typing.Optional[typing.List[float]] = Field(default=None, description='Deprecated [dx, dy, dz]; null when using target_position')
    message: typing.Optional["CoordMessage"] = None

class CoordMessage(BaseModel):
    payload: typing.List[float]
    channel: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
